### ISSUE TITLE
Player de música

### ISSUE THREAD

**Issue by leonardo-marinho** [joaovjusto/gmod-ls#3]
Desenvolver função para pegar os arquivos de áudio de uma pasta pública e executá-los.

O usuário colocará os arquivos na pasta (a ser definida) e renomeará arquivo por arquivo no padrão _audioN-Nome qualquer_, sendo N um numero.

Por exemplo: _audio1-xuxa so para baixinhos.mp3_

Executar na ordem _audio1_, _audio2_, _audio3_ [...]
Deve suportar formatos .wav, .ogg e .mp3.
Utilizar tag HTML _audio_  como player.

Todo conteudo do nome do arquivo deverá ser exibido no widget Music, exceto a identificação do áudio e a extensão.

Por exemplo: _audio1-xuxa so para baixinhos.mp3_
![image](https://user-images.githubusercontent.com/50488688/104229041-75fff380-542a-11eb-8b7e-87f64435a130.png)

**Comment by leonardo-marinho** [comment]
Limitar-se a arquivos ogg por limitação do jogo

**Comment by dev-marinho** [comment]
Commit 4a1a366

**Comment by leonardo-marinho** [comment]
Commit 4a1a366
